DROP TABLE IF EXISTS user;

CREATE TABLE user
(
    id BIGINT(20) NOT NULL COMMENT '主键ID',
    name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    age INT(11) NULL DEFAULT NULL COMMENT '年龄',
    email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS log;

CREATE TABLE log
(
    id INT(11) NOT NULL COMMENT '主键ID',
    tenant VARCHAR(30) NULL DEFAULT NULL COMMENT '租户',
    biz_key VARCHAR(200) NULL DEFAULT NULL COMMENT '业务键',
    biz_no VARCHAR(200) NULL DEFAULT NULL COMMENT '业务编号',
    operator VARCHAR(200) NULL DEFAULT NULL COMMENT '操作人',
    action VARCHAR(200) NULL DEFAULT NULL COMMENT '操作',
    category VARCHAR(200) NULL DEFAULT NULL COMMENT '分类',
    create_time timestamp NULL DEFAULT NULL COMMENT '创建时间',
    detail CLOB NULL DEFAULT NULL COMMENT '详情',
    PRIMARY KEY (id)
);